version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nurettin@123
      - MSSQL_RPC_PORT=135
      - MSSQL_DISABLE_TLS=1
    ports:
      - "1433:1433"
    networks:
      - appnet

  api:
    build:
      context: ./API
    container_name: dotnet_api
    ports:
      - "8080:8080"   # Ä°stersen burayÄ± "0.0.0.0:8080:8080" yapabiliriz
    environment:
      ASPNETCORE_URLS: "http://+:8080"
    networks:
      - appnet

  client:
    build:
      context: ./Client
    container_name: react_client
    ports:
      - "0.0.0.0:3000:80"   # ðŸ“Œ Ã–NEMLÄ°: dÄ±ÅŸ IPâ€™den eriÅŸim iÃ§in
    depends_on:
      - api
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
